### ISSUE TITLE
Fix optional character behaviour

### ISSUE THREAD

**Issue by probil** [probil/v-mask#126]
### V-Mask and Vue versions
1.3.2, 2.5.3

### Reproduction Link
https://github.com/probil/v-mask/blob/master/src/__tests__/format.test.js#L57

### Steps to reproduce

1. Use mask with optional character `##?#-A`
2. Type `12L`

### What is Expected?
String formatted as `12-L`

### What is actually happening?
String formatted as `12`

**Comment by jwkicklighter** [comment]
Is there any update on this?

**Comment by probil** [comment]
Fixed in version `v2.0.0` and up 🎉
