### ISSUE TITLE
Ability to define mask placeholders

### ISSUE THREAD

**Issue by probil** [probil/v-mask#128]
It would be nice to have ability to add/remove/replace custom mask placeholders. 
Predefined placeholders are not enough in some cases. 
Currently the idea is to pass placeholder definitions to the plugin options. This will apply to all masks.

```js
Vue.use(VueMask, { 
  placeholders: {
    // define new placeholder
    'S':  /[a-z]/.test,

    // remove existing placeholder
    '#': null,

    // replace existing placeholder
    'N':  /[a-z]/.test,
    },
  },
});
```

Plus we should be able to do the same for one mask only.
```vue
<template>
  <input v-mask="['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]" />
</template>
```

TODO:
 - [ ] Accepts array of regular expression directly
 - [ ] Add/remove/replace global mask placeholders
 - [ ] Update README

Test cases: 
 - Test for uppercase/lowercase values #67 (3 likes)
 - Test for cyrillic characters #230 (4 likes)
 - Correct time mask #443
 - Ability to define mask like `0(6|7)-##-##-##-##` #184 (5 likes)

**Comment by Code8525** [comment]
```
Vue.use(VueMask, { 
  placeholders: {
    // define new placeholder
    'S':  {
                pattern: /[0-9a-zA-Z]/, 
                transform: function (e) {
                    return e.toLocaleUpperCase()
                }
          }
    },
  },
});
```
Hello!
You need something like this to have maximum flexibility.
No way to raise to uppercase
