### ISSUE TITLE
Cannot initialize mask with a parenthesis 

### ISSUE THREAD

**Issue by alicesouto** [probil/v-mask#13]
When using a phone mask like that;
     v-mask="'(##) #####-####'"
It first input key is not recognized.

**Comment by c01nd01r** [comment]
+1

**Comment by ribamartins** [comment]
Hi,

Replace the code in the format.js file with the code below:

==============================================

'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (data, mask) {
  if (!mask) return data;

  var text = '';
  for (var i = 0, x = 1; x && i < mask.length; ++i) {
    var c = data.charAt(i);
    var m = mask.charAt(i);

    switch (m) {
      case '#':
        if (/\d/.test(c)) {
          text += c;
        } else {
          x = 0;
        }break;
      case 'A':
        if (/[a-z]/i.test(c)) {
          text += c;
        } else {
          x = 0;
        }break;
      case 'N':
        if (/[a-z0-9]/i.test(c)) {
          text += c;
        } else {
          x = 0;
        }break;
      case 'X':
        text += c;break;
      default:
        text += m + (data.length == 1 ? c : '');break;
    }
  }
  return text;
};

**Comment by alicesouto** [comment]
I try it @ribamartins, but It did not change anything.

**Comment by shaneeza** [comment]
+1

**Comment by probil** [comment]
Hi, @alicesouto 
I will check later today

**Comment by kcolls** [comment]
+1

**Comment by alicesouto** [comment]
@probil Thanks! I hope hearing from you soon

**Comment by kcolls** [comment]
FWIW, the code pasted by @ribamartins worked for me. Make sure to replace the dist version and not src.

**Comment by alicesouto** [comment]
Thanks @kcolls. It actually worked well!

**Comment by probil** [comment]
Re-opened until not merged. Changes will uppear in npm soon

**Comment by probil** [comment]
Thanks @alicesouto, @kcolls, @ribamartins

**Comment by c01nd01r** [comment]
https://niksmr.github.io/vue-masked-input/
Good component for input mask

**Comment by renanpro03** [comment]
same here, waiting for merge. Thanks

**Comment by probil** [comment]
Should be fixed in `v1.0.3`. Please, check it out
