### ISSUE TITLE
Add filter to format static values

### ISSUE THREAD

**Issue by probil** [probil/v-mask#147]
It might be useful to have ability to format and display static text (without input / v-model) etc

```html
<span>{{ '9999999999' | VMask('(###) ###-####') }}</span>
<!-- should render -->
<span> (999) 999-9999</span>
```

**Comment by alokpant** [comment]
Hey @probil, can I look into this? I am looking for first contribution.

**Comment by alokpant** [comment]
@probil Thank you. Will look into it during weekend.

**Comment by clemsontiger** [comment]
any update on this? went to do this and hadn't even considered it was only available for inputs

**Comment by probil** [comment]
@clemsontiger It's not ready yet. No news from @alokpant 
In any case it's easy to implement. You can add it by you self and create PR
