### ISSUE TITLE
Press And hold key overrides mask limit

### ISSUE THREAD

**Issue by fimdomeio** [probil/v-mask#16]
for a mask that is something like v-mask="'##h##'" if I press the key 1 continuously the input will be 11h111.
Don't know if it matters but I have a fast repeating rate in my keyboard.

**Comment by probil** [comment]
I will check. Thanks for your feedback/response

**Comment by probil** [comment]
Please, provide some info about your system. At least, library version, vue version, browser and system

**Comment by probil** [comment]
Can't reproduce on my machine

**Comment by fimdomeio** [comment]
"v-mask": "^1.0.2",
"vue": "^2.0.5",
Mac, Chrome 56. Just noticed v-mask is not working at all on Firefox. This is probably a problem on my side, I'll investigate further.

From testing I realized the problem is actually a bit different from my initial explanation. Chrome is returning one more character than expected in v-model. Inspecting further it starts to look like I shouldn't be using v-model at all but somehow hooking up to data-previous-value.

So I would say this is probably not a bug, but I would suggest adding to the documentation an example of outputing the value..

I'll look more deeply into this in the next few days.

**Comment by fimdomeio** [comment]
A video of my issue.
https://fimdomeio.com/p/booknatura/v-mask-trouble.m4v

**Comment by probil** [comment]
Aha! I got it. Displayed value and mask value is different. Thanks, @fimdomeio

**Comment by probil** [comment]
Please, check the `v1.1.0` and up. Should be fixed
