### ISSUE TITLE
v-model and v-mask

### ISSUE THREAD

**Issue by almaweb** [probil/v-mask#18]
Hello,

Is this work with v-model ?
I can't make it work with simple input with v-model:
```html
<input type="text" v-model="someModel" v-mask="'####-##'">
```

Thanks

**Comment by probil** [comment]
Hi, @almaweb

Yeah, it works with `v-model`. Please, provide more details to find why it does't work for you.

**Comment by cimigree** [comment]
I am having the same issue with v-model. If I take the v-model out, the (phone)mask works. If the v-model is there, then it doesn't work.

**Comment by odranoelBR** [comment]
Yes, i am having too. Works only whitout v-model.

**Comment by probil** [comment]
Please, check the version `1.1.0` and up. Should be fixed
