### ISSUE TITLE
Feature request : Give the ability to give two or multiple choices

### ISSUE THREAD

**Issue by darkylmnx** [probil/v-mask#184]
Thanks for you great directive, i'm facing an issue here, I would like to add some options between two numbers but I can't get how to do this so I guess it's because maybe I can't ?

Here's the problem, I have a field with a phone number, the phone number must be in the format : 
`06-##-##-##-##` OR `07-##-##-##-##`.

When I trye something like :` 0(6|7)-##-##-##-##`, it doesn't work (as expected I guess) because it thinks the parenthesis is part of the mask while I don't want it to be, I just want to express a choice between to hard coded digits.

Any way to do this actually or could this be a good feature request ? Eventually is could be [6|7] instead, or something like `@(6|7)` where `@()` would be the "escaper" so that you know it's not part of the mask.

**Comment by maxjf1** [comment]
i need this too, to make an mask such as ####-#### and #####-####

**Comment by probil** [comment]
Feature is part of #128 now. Please continue discussion there
