### ISSUE TITLE
Optional Number

### ISSUE THREAD

**Issue by renanpro03** [probil/v-mask#21]
Hi, using jquery mask on my old projects I was able to do something like this:
$(".phone").mask("(99) 9999-9999?9");
With an optional number using the question mark "?", how to do it using v-mask?
Thanks

**Comment by probil** [comment]
Is not supported for now

**Comment by gabrielbuzziv** [comment]
+1

**Comment by DawTaylor** [comment]
PR #27 should cover this.

**Comment by gabemule** [comment]
+1

**Comment by cleitonsouza** [comment]
+1

**Comment by probil** [comment]
Merged in `v1.2.0`
