### ISSUE TITLE
not work without a default first char

### ISSUE THREAD

**Issue by gbgelado** [probil/v-mask#22]
not work
```
<md-input v-model='form.client.cpf' required v-mask="'###.###.###-##'"></md-input>
```
the field is: "#1"

work
```
<md-input v-model='form.client.cpf' required v-mask="'/###.###.###-##'"></md-input>
```
the field is: "/123.123.123.12"
```
<md-input v-model='form.client.cpf' required v-mask="'-###.###.###-##'"></md-input>
```
the field is: "-123.123.123.12"
```
<md-input v-model='form.client.cpf' required v-mask="'(###.###.###-##'"></md-input>
```
the field is: "(123.123.123.12"

Work with blank space too

**Comment by danieldnl** [comment]
same problem here

**Comment by jorgevilaca82** [comment]
fast workaround.
Downgrade to 1.0.2

**Comment by JuliusCesarius** [comment]
Should be resolved with pull request #25

**Comment by probil** [comment]
I will merge #25 today

**Comment by probil** [comment]
#23 Merged (what does the same thing as #25) 
Check it out in `v1.0.4`

**Comment by fimdomeio** [comment]
I can confirm that 1.0.4 fixes the issue.

**Comment by probil** [comment]
Thanks, @fimdomeio
