### ISSUE TITLE
Feature request : Add Cyrillic characters for v-mask

### ISSUE THREAD

**Issue by webspilka** [probil/v-mask#230]
Thanks you for cool plugin.
### What is Expected?
Can you add support Cyrillic letter for v-mask="'ЯЯЯЯ'" ?
Probably also it was, it would be nice to indicate the Cyrillic alphabet or Latin alphabet,
something like v-mask="'(A|Я)(a|A|Я|я)'" 
### What is actually happening?
v-mask="'AAAA'" not support Cyrillic character

**Comment by probil** [comment]
Thanks for your issue @webspilka
We need to update regexp to make it work. 
It seems like it's a good candidate for the next minor release ;)

**Comment by probil** [comment]
Feature is part of #128 now. Please continue discussion there
