### ISSUE TITLE
v-mask not working in android chrome with v-validate

### ISSUE THREAD

**Issue by purvishah165** [probil/v-mask#253]
V-Mask and Vue versions
1.3.2, 2.5

` <input type="tel" v-mask="'## ### ### ###'" name="ABN" v-model="abnDetails.abn" v-validate="{ required: true, min: 14}" :class="{'is-danger': errors.has('ABN') }">
                 `

### What is Expected?
Input should be in form XX XXX XXX XXX.

### What is actually happening?
In chrome in OnePlus3 the input does not format and displays as XXXXXXXXXXXXX without spaces.

**Comment by faenir** [comment]
Same problem.

**Comment by kssioalmeida** [comment]
I have the same problem.

**Comment by probil** [comment]
There is a well-know issue on mobile chrome. It's not particularly related to `v-validate`

**Comment by nelsonad** [comment]
@probil What is the well-known issue in mobile chrome?

**Comment by nelsonad** [comment]
I found one workaround for this issue is to configure v-validate to validate the field on the change event rather than input.
`data-vv-validate-on="change"`

**Comment by farzadso** [comment]
The issue still occurs for me on the latest version of v-mask (2.0.2)

**Comment by Timures** [comment]
Still not work in mobile chrome - version of v-mask: "^2.3.0",
