### ISSUE TITLE
Can't handle the currency inputs, tied to specify length of numbers

### ISSUE THREAD

**Issue by Tecayehuatl** [probil/v-mask#272]
I am using the latest version of v-mask(1.3.2), and I can't figure out the way v-mask can handle the currency, my issue is if i have the amount of: 21500 (raw) and I apply the mask '###,###' I am force to have 3 numbers, I am not sure if v-mask can handle amounts with no specify the lenght of numbers(###) and format itself correctly?

You can check my example:
https://codepen.io/tecayehuatl/pen/gBPypo?editors=1010

**Comment by probil** [comment]
Hi, @Tecayehuatl 
Thanks for your issue. Currency mask is not currently supported. 
This plugin is for simple cases. Currency support requires major rewrite. Try to use different library for that purpose

Duplication of #15
