### ISSUE TITLE
Bug mask number after static character

### ISSUE THREAD

**Issue by atiksoftware** [probil/v-mask#282]
Hi,
if i want use phone format like "05xx xxx xx xx", i cant use first 2 chars static "05",
because if i use mask "05## ### ## ##", i cant write "5" for 3.char after static 5,

first 2 chars have to "05"
mask: "05## ### ## ##",
number: "0555 541 23 25"

**Comment by probil** [comment]
It seems like it's related to #53

**Comment by probil** [comment]
Should be fixed in `v2.0.0` and up.
Please check new version let me know if it is working well for your case
