### ISSUE TITLE
Enable/disable mask on condition

### ISSUE THREAD

**Issue by Alex-Sokolov** [probil/v-mask#303]
Sometimes mask need to be apply to some fields on condition. For now we solve this by duplicating markup with all attributes:
```html
<input
    v-if="field.mask"
    v-mask="field.mask"
    v-model="value"
    ... another attributes ...
/>
<input
    v-else
    v-model="value"
    ... another attributes ...
/>
```
In documentation there is `X` character for any symbol, but it reduce total characters count

Will be useful when possible to set mask on condition. For example:
```html
<input
    v-mask="field.mask || false"
    v-model="value"
/>

<!-- OR -->
<input
    v-mask="field.mask || '*'"
    v-model="value"
/>

<!-- OR -->
<input
    v-mask="someComputedMask"
    v-model="value"
/>
```

**Comment by Alex-Sokolov** [comment]
@probil Hi! Can you say when it's possible to see this feature in v-mask?

**Comment by stephanUllenboom** [comment]
I need this feature, too.
My use case: 
I have an input field for a personal number which have client based masks.

Client 1:
`######`
Client 2:
`9#####`
Client 3:
no-mask
Client 4:
`C-######`

In case for the client 3 I want to disable the mask.
The current workaround I use two input fields 🙁

**Comment by Nfinished** [comment]
You can disable masking by passing a blank string to the directive.

`<input v-model="someValue" v-mask="''" />`

**Comment by 7rows** [comment]
> [](https://jsfiddle.net/k9r62uem/)

this example not working, when mask disabled, i don't input any chars

**Comment by probil** [comment]
Confirmed. Sounds like a bug

**Comment by probil** [comment]
It expected to work as @Nfinished example

**Comment by Kurzdor** [comment]
@probil I don't think so.
https://www.dropbox.com/s/38iegtpai33p6pn/ScreenRec_20190819_235433.mp4?dl=0

Xiaomi Mi A1, Android 9 Pie
Chrome 76.0.3809.11

**Comment by dionisiatara** [comment]
Hey there @probil, would this be implemented sometime soon? Thanks!

**Comment by SkipTyler** [comment]
Is there any workaround?

**Comment by RonaldJerez** [comment]
> Is there any workaround?

@SkipTyler try vue-input-facade
https://github.com/RonaldJerez/vue-input-facade

**Comment by leo-rojas** [comment]
As a workaround, when adding the directive, you can check the value of the mask before applying it:
```
import Vue from 'vue';
import { VueMaskDirective } from 'v-mask';

Vue.directive('mask', function(el, binding) {

	if(!binding.value)
	{
		return;
	}

	VueMaskDirective.bind(el, binding);
});
```

Seems to be working as usual

**Comment by ems1985** [comment]
+1 
shouldnt be too hard to change the code to ignore null or undefined masks...

**Comment by ems1985** [comment]
+1 
would be nice to change the code to ignore null or undefined masks...

**Comment by baitkul** [comment]
> Is there any workaround?

As a workaround before **undefined** mask will be implemented, I use:

```
<template>
  <input
    v-model="value"
    v-mask="isMaskEnabled ? '##-##-##' : 'X'.repeat(100)"
  />
</template>
```

**Comment by KonstantinKudelko** [comment]
Hey there!

Any suggestion?
