### ISSUE TITLE
Disable data-previous-value

### ISSUE THREAD

**Issue by SkipTyler** [probil/v-mask#309]
Hey.
I use dynamic masks in my project.

After switching them, the value of the country code hangs in my input.

But I would like to see a placeholder there.

How to disable it?

here is my input
Connected in a standard way, globally.

```
 <input type="text"
               v-mask="mask"
               v-model="value"
               :placeholder="placeholder"
             >

```

Well, an example of a mask

`"mask": "+62(8##)###-####",`

**Comment by probil** [comment]
Hi, @SkipTyler 

I will try to take a look soon

Thanks for your issue

**Comment by probil** [comment]
@SkipTyler Can you please check is it possible to reproduce the issue in v2?

**Comment by probil** [comment]
`data-previous-mask` was removed in `v2`
