### ISSUE TITLE
Space added at end of input

### ISSUE THREAD

**Issue by diffused** [probil/v-mask#33]
Is there a way to prevent a space being added at the end of an input, specifically on the date masked input.

On the demo page, try adding a date in and a space appears at the end if you type in a date: eg 12/12/1980
https://rawgit.com/probil/v-mask--demo/master/dist/index.html

**Comment by probil** [comment]
Hi, @diffused 

There is no date masked input, there is only date AND time:
`##/##/#### ##:##` (mask)
Date-only can be achived by using this mask:
`##/##/####`
