### ISSUE TITLE
Problems with "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by egorikas** [probil/v-mask#34]
Hi.

I've started to use your library recently. And unfortunately faced a problem with `"Cannot read property 'length' of undefined"` for `previousValue` in `updateValue` method. 
 I suppose, that problem appears when some component values are set in the `beforeMount` method. 

I've tried to fix this problem.

Thank you

**Comment by sneila** [comment]
add "typeof previousValue != 'undefined' " on line 46 in dist/index.js to solve it:

...
if (force || value && value !== previousValue && typeof previousValue != 'undefined' && value.length > previousValue.length) {
...

**Comment by egorikas** [comment]
@sneila Thank you for your comment. I'll do it

**Comment by probil** [comment]
I will apply this fix ASAP

**Comment by arthurvasconcelos** [comment]
I am facing the same problem. Thanks for the solution @sneila.

Excellent lib @probil.

**Comment by probil** [comment]
@arthurvasconcelos just merged and published to `npm`

**Comment by probil** [comment]
Should be fixed in `v1.1.1`. Under review now
