### ISSUE TITLE
NPM reports security issues

### ISSUE THREAD

**Issue by tspratt** [probil/v-mask#374]
### V-Mask and Vue versions
npm version: 6.4.1
Vue version: 2.6.6
v-mask version: 1.3.3

### Steps to reproduce
1. run "npm install v-mask --save"

### What is Expected?
No security vulnerabilities found

### What is actually happening?
npm reports: "found 7 moderate severity vulnerabilities"

**Comment by probil** [comment]
@tspratt 👋 
npm warns you about `jest` and I use `jest` only for testing.
Those are not real security vulnerabilities.  They will never affect you or your users. 

I'm freaked out of JavaScript security  🤕
A lot of false positives.

**Comment by probil** [comment]
In any case I'm going to merge a new version of jest into master soon

**Comment by probil** [comment]
Will be fixed in `v2.0.1`
