### ISSUE TITLE
Wanted only to show nor format

### ISSUE THREAD

**Issue by amansharma2019** [probil/v-mask#379]
The mask edits the Value which i dont want to save in database .
but i not found any feature for this .

**Comment by amansharma2019** [comment]
The mask edits the Value which i dont want to save in database .
but i not found any feature for not for this .

**Comment by probil** [comment]
Hi @amansharma2019 
Library is supposed to be used for editing. 

If you need just displaying use a simple element without v-model (e.g. `<p>` or `<span>`)
