### ISSUE TITLE
IE 9+: Unable to set property 'mask' of undefined or null 

### ISSUE THREAD

**Issue by jpozosrc** [probil/v-mask#39]
When I test v-mask on IE10 I get

Unable to set property 'mask' of undefined or null reference

I works in Chrome and Firefox with no issues
I have Polyfill enabled in my application.

I resolved these isues by making the changes below:
Bbasically using getAttribute on elements instead of the dataset notation, which is only supported on IE 11+

```
 function updateValue(el) {
  var force = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;
  var value = el.value,
      //_el$dataset = el.dataset,
      //_el$dataset$previousV = _el$dataset.previousValue,
      _el$dataset$previousV = el.getAttribute('data-previous-value'),
      previousValue = (_el$dataset$previousV === undefined ? "" : _el$dataset$previousV,
      //mask = _el$dataset.mask;
      mask = el.getAttribute('data-mask');


  if (force || value && value !== previousValue && value.length > previousValue.length) {
    el.value = (0, _format2.default)(value, mask);
    (0, _utils.trigger)(el, 'input');
  }

  //el.dataset.previousValue = value;
  el.setAttribute('data-previous-value', value);
}

function updateMask(el, mask) {
  //el.dataset.mask = mask;
  el.setAttribute('data-mask', mask)
} 
```

**Comment by probil** [comment]
I don't even think somebody still using IE9 or IE10. Hehe. 😃 
Ok. I will add polyfill :)

**Comment by dubcanada** [comment]
In my project I just added element-dataset polyfill. Except the mask still doesn't work.

**Comment by mesutgok** [comment]
I haved some problem

**Comment by victorwpbastos** [comment]
I submitted a PR for this. PR #43

**Comment by shrpne** [comment]
Does anyone try something like [Polyfill.io ](https://polyfill.io/v2/docs/) or [autopolyfiller](https://github.com/azproduction/autopolyfiller) to fix it?
I think, if it is possible to polyfill automatically, then we should not complicate codebase of v-mask and make it less maintainable

**Comment by gmhenderson** [comment]
I have the same problem as @dubcanada. Unless I literally paste the polyfill code into the v-mask module, I can't get it to work. It might be the way I'm using Webpack, but would be great to get this working in v-mask itself.

**Comment by probil** [comment]
IE 9 won't be supported, it's an ancient browsers and it must die already. Look for alternatives if you still need support for IE < 11
