### ISSUE TITLE
Not applying mask on Android mobile devices

### ISSUE THREAD

**Issue by lennoximus** [probil/v-mask#411]
### V-Mask and Vue versions
1.3.3, 2.6.10

### Reproduction Link

Any usage examples. Let it be your page: https://v-mask-demo.netlify.com/
### Steps to reproduce

1. Find an Android mobile device.
2. Visit the link mentioned above.
3. Start typing in any input.
4. See that functionality is not working.

### What is Expected?
Mask to be properly applied to the input value.

### What is actually happening?
We can see a raw (neither modified nor masked) value, that we've entered, despite the mask.

My best approach to somehow solve this thing, was just calling `this.$forceUpdate()` after every input event firing. As far as I can tell there is something wrong with `componentUpdated` hook, which is not called on android devices, so all related methods are just not executing at all.

Maybe there is a better way to solve this thing, I'm not aware of. If so, hit me up.

Cheers.

**Comment by nelsonad** [comment]
Are you using v-validate on the fields?

**Comment by lennoximus** [comment]
@nelsonad no, I am not. Though, I was using vuelidate for validation purposes, so there must be some kind of a link in these cases.

**Comment by probil** [comment]
Hi, @lennoximus 👋 

Can you provide a browser name, browser version and android version?

There is a lot browsers on android.

Thanks for your issue

**Comment by lennoximus** [comment]
Hello, @probil.
Since [v2.0.0](https://github.com/probil/v-mask/releases/tag/v2.0.0) of `v-mask` this issue is no longer reproducible and fixed due to migrating from `pureMask` and use `text-mask-core`, I guess. No need in keeping this issue opened now. 
Thanks for the support.

**Comment by probil** [comment]
Thank for the response @lennoximus

**Comment by alexcomo95** [comment]
I have v-mask ^2.0.2 and I can't make it work on Chrome for Android version 77.0.3865.116.
It won't work on Samsung Internet either (version 10.1.01.3).
Not sure what I can do about that, since it works on Chrome and Firefox for PC.

**Comment by nelsonad** [comment]
> I have v-mask ^2.0.2 and I can't make it work on Chrome for Android version 77.0.3865.116.
> It won't work on Samsung Internet either (version 10.1.01.3).
> Not sure what I can do about that, since it works on Chrome and Firefox for PC.

Hi Alex.

Are you using v-validate by chance?

**Comment by alexcomo95** [comment]
Hi Nelson,

No, I don't use that tag. For more context, I use Vuetify. It doesn't seem to use it behind the scene either. The v-mask is included in a v-text-field. It works well on PC so I expected the same behavior on mobile.

But thinking about it, I'm not even sure if it was expected to work with Vuetify. Let me know if I should open a different ticket.

**Comment by alexcomo95** [comment]
UPDATE:

I just tried with <input> and the result is exactly the same. So it has nothing with Vuetify.

**Comment by leandrocodes** [comment]
I'm currently facing the same issue. Using vue validate too.
