### ISSUE TITLE
Cloned object from vuex not been applied the mask

### ISSUE THREAD

**Issue by Underzzoo** [probil/v-mask#44]
Hello to all

I receive an object from my VUEX store, if i clone that object (in different method, JSON.parse / stringify or lodash / underscore clone function), the mask not apply.

If i remove the clone function OR the JSON.parse() / stringify() from the code, the mask works very well, but this break all my application data, because modify without a mutation.

Anyone have a solution for this ?

Thanks

```
computed: {
    user () {
      // let user = JSON.parse(JSON.stringify(this.$store.getters.getUser))
      let user = clone(this.$store.getters.getUser)
      if (user.gender) {
        this.gender = user.gender
      }
      return user
    },
    address () {
      return JSON.parse(JSON.stringify(this.$store.getters.getAddress))
    }
  }
```

[Problem GIF image](https://ibb.co/db0LO5)

**Comment by probil** [comment]
Sounds like a bug

**Comment by probil** [comment]
You can fix this by appling getter and setters for computed property
Check the approach here:
https://vuex.vuejs.org/en/forms.html#two-way-computed-property
Re-open the issue if you still have the issue
