### ISSUE TITLE
mask Time 00:00-24:00

### ISSUE THREAD

**Issue by 7rows** [probil/v-mask#443]
Hi, how i can created mask with only 00:00-24:00;
if i use ##:##-##:##, i can past in input 99:99-99:99

**Comment by probil** [comment]
Hi @7rows 
Thanks for your issue. In current version it's not supported but I'm currently working on the ability to define custom replacer and pipelines which will allow to achieve that

**Comment by 7rows** [comment]
Круто, я у себя пока сделал параметр time и там регуляркой проверяю

**Comment by andrewleykin** [comment]
> Круто, я у себя пока сделал параметр time и там регуляркой проверяю

Привет, как проверяешь? покажи пожалуйста код

**Comment by probil** [comment]
Feature is part of #128 now. Please continue discussion there
