### ISSUE TITLE
Default value Any simbol

### ISSUE THREAD

**Issue by 7rows** [probil/v-mask#445]
Hi, How do we make sure that if we don't have a patttern entered, we can enter anything without restriction?

Rus
Как сделать так, чтобы, если у нас не введен patttern, то  можно вводить все что угодно, без ограничения?

**Comment by zefexdeveloper** [comment]
I wanted to know the same.

**Comment by probil** [comment]
Thanks for your issue.
This functionality is not supported just yet. There is a PR and I'm going to release as part of the next minor version.

BTW It's duplication of #303
Please continue discussion there.
