### ISSUE TITLE
Directive on chrome browser (android) not apply the mask. 

### ISSUE THREAD

**Issue by henriquecustodia** [probil/v-mask#454]
Directive on chrome browser (android) not apply the mask. 

On desktop (macOS, windows, etc) using chrome and iOS 10 (chrome and safari), works fine. 

I think the `componentUpdated` hook of directive is "overriding" the value (masked) to a value not masked after the parent component has a change. 

Seems that problem has relation with this code:
```js
 function triggerInputUpdate(el) {
    var fn = trigger.bind(null, el, 'input');

    if (isAndroid && isChrome) {
      setTimeout(fn, 0);
    } else {
      fn();
    }
  }
```

Changing the code above to: 
```js 
   function triggerInputUpdate(el) {
        trigger.bind(null, el, 'input')();
    }
 ```
Seems fix the bug. 

### V-Mask and Vue versions
2.0.2, 2.6.10

### Steps to reproduce

1. Use the directive on Chrome for Android 
2. Type a value 
3. The mask won't be applied

**Comment by g7tro4w** [comment]
I have the same issue. Chrome 78, Android 5.1

```
<input
  v-model="authTelephone"
  type="tel"
  v-mask="'+7 (###) ###-##-##'"
  placeholder="+7"
  name="phone"
  class="txt-field"
/>
```

**Comment by zefexdeveloper** [comment]
It's not working for me either, it only applies the mask when focusing the input

**Comment by EdwardAckerman** [comment]
Same issue here, on iphone works fine but not on android

**Comment by cchooley** [comment]
Exact same issue as well. We've only started experiencing this issue on the devices we're testing on roughly a week or so ago, but it is indeed happening and only on Android chrome.

Any efforts to address this issue would be greatly appreciated as this is a GREAT package overall and we really like using it in my shop.

**Comment by ekeyte** [comment]
@henriquecustodia and friends: I have opened a PR (above) to address this issue, but I am unable to easily test it since every device I own is an Apple product. Any chance you guys could try to grab that tag and see how it performs?

**Comment by mlaw93** [comment]
Just FYI, this resolved same issue on Chrome (OS X) when in debug and using "Toggle Device Toolbar" feature
