### ISSUE TITLE
Using v-mask with UMD(Browser)

### ISSUE THREAD

**Issue by developeralp** [probil/v-mask#470]
Hello everybody,

I imported v-mask same with UMD example.
Like this:

`<script src="https://cdn.jsdelivr.net/npm/v-mask/dist/v-mask.min.js"></script>`

I tried both of them to import:

`Vue.use(VueMask.VueMaskPlugin);`
`Vue.directive('mask', VueMask.VueMaskDirective);`

I need this element to be masked:
`                      <v-text-field :counter="11" :rules="phoneRules" name="phone" label="Phone Number" prepend-icon="phone" type="number" v-mask="'####-##'"></v-text-field>`

But I could not get it work. What should I do?

**Comment by developeralp** [comment]
Solved. It was my fault.

**Comment by probil** [comment]
Yeah, I should mention about it somewhere in the docs.
Thanks for your issue @developeralp 👍
