### ISSUE TITLE
VueMaskFilter isn't being exported in the /dist version.

### ISSUE THREAD

**Issue by brandonpittman** [probil/v-mask#474]
VueMaskFilter isn't being exported in the /dist version.

**Comment by probil** [comment]
Hi, @brandonpittman 
VueMaskFilter haven't been released yet :) I'll do that right away

**Comment by brandonpittman** [comment]
@probil Thanks! It was in the docs, so I attempted to use it, but the export wasn't available.

**Comment by probil** [comment]
@brandonpittman Just released `v2.1.0`, check it. Let me know if you still experience the issue
