### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by pedroskakum** [probil/v-mask#48]
Is possible use the plugin in another tag, for example, 
```
<p>, <td>, <dd>
```
...thank you

**Comment by probil** [comment]
Currently - no and I don't think it's needed. Just use computed property or filter instead. If you think there are some useful cases - go ahead and explain. I'm open to new ideas. 💡

**Comment by pedroskakum** [comment]
You are right, I am using filters to put masks on tables, but you are right, there is no reason to do this, since a filter is lighter and simpler, just for the visualization.

Another question, have not I had time to test yet? The behavior of the plugin after submerging the data and remove the mask or continue with it in the data?

**Comment by probil** [comment]
> Is there any form of remover like masks for a submission of data?
Create new issue please.
