### ISSUE TITLE
v-mask should support :v-mask="getMask('phone')"

### ISSUE THREAD

**Issue by gvdonovan** [probil/v-mask#49]
Rather than having v-mask="'### ###-####'" for example for a phone multiple times it should support :v-mask="getMask('phone')" so the actual mask can be changed in one place :)

**Comment by probil** [comment]
`v-mask` supports change mask on-the-fly.

Check the demo here:
https://rawgit.com/probil/v-mask--demo/master/dist/index.html
And the code here:
https://github.com/probil/v-mask--demo/blob/master/src/App.vue#L77

**Comment by probil** [comment]
> `:v-mask="getMask('phone')"`
Functions is not really a Vue-way of handling this. Consider using computed properties or data values.

**Comment by edgardleal** [comment]
This works without the `: `

Ex.: `<input v-mask="getMask('phone')" v-model="phone"/>`

**Comment by probil** [comment]
@edgardleal Nice catch! Thanks
