### ISSUE TITLE
First smart digit entered, is it possible?

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [probil/v-mask#505]
Thanks a lot for this plugin! It helped me solve the problem of installing a mask for my phone! I apologize in advance for asking the question here, but I could not find the answer.

In my case, the first digit of the phone is ``+7``. My mask looks like this: ``v-mask = "'+ 7 (###) ### - ## - ##'"``.

I expect that if I typed the number ``7``, then it will not be written in parentheses, but before them. That is, if I typed seven, then I get ``+7``, if I typed any other number, then seven is automatically substituted, and the number I entered is written in parentheses.

How can I implement this?

**Comment by kylemilloy** [comment]
I would look at the
