### ISSUE TITLE
Distribute v-mask as a directive

### ISSUE THREAD

**Issue by shrpne** [probil/v-mask#51]
I think it will be better to distribute v-mask as a directive, not as a plugin, so it can be used in components too, like `directives: { mask: VueMask }`

If someone want to use it on global constructor, it will be available as `Vue.directive('mask', VueMask)`. 

So this will be more flexible, but still simple as current `Vue.use(VueMask)`

**Comment by probil** [comment]
🤔 Actually it's possible to distribute it as plugin and directive at the same time. 
Just change few lines of code
PR is welcome if you want to get if faster
