### ISSUE TITLE
Filter not working on null values

### ISSUE THREAD

**Issue by madsongr** [probil/v-mask#510]
### V-Mask and Vue versions
2.2.3, 2.6.12

### What is Expected?
(55) 5 5555-5555 
### What is actually happening?
(

I'm using `v-mask` in browser from UMD and I get data from database and looping through it using `v-for`. I use mask as a filter but it's getting empty when I apply the mask. Only `(` is displayed on the screen;

`<p>Contato: {{ 'user.cellphone' | VMask('(##) # ####-####') }}</p>`

main.js:
`Vue.use(VueMask.VueMaskPlugin);`

Is there any other configuration that must be done?

**Comment by probil** [comment]
Hi @madsongr 
I guess it's because you masking string `'user.cellphone'` and not the actual value stored in `user.cellphone`.

Try this instead:
```html
<p>Contato: {{ user.cellphone | VMask('(##) # ####-####') }}</p>
```

**Comment by madsongr** [comment]
> Hi @madsongr 
> I guess it's because you masking string `'user.cellphone'` and not the actual value stored in `user.cellphone`.
> 
> Try this instead:
> ```vue
> <p>Contato: {{ user.cellphone | VMask('(##) # ####-####') }}</p>
> ```

Hi. I tried that too but I get an error.

I'll check the specific error and post here in a few hours but it was something like "cannot get length of null" but the value is not null.

**Comment by madsongr** [comment]
Hi @probil. I tried that too but I get an error.

`Cannot read property 'length' of null.`

User data:

![image](https://user-images.githubusercontent.com/4735867/105398962-b9fcb080-5c01-11eb-9247-12846484a8c5.png)

**Comment by probil** [comment]
It's because your user is not an object:
```vue
<p>Contato: {{ userData[0].cellphone | VMask('(##) # ####-####') }}</p>
<!-- or better -->
<p v-for="user of userData">Contato: {{ user.cellphone | VMask('(##) # ####-####') }}</p>
<!-- or -->
<p v-for="(user, index) of userData">Contato: {{ userData[index].cellphone | VMask('(##) # ####-####') }}</p>
```
If it still doesn't work for you, bring me json of your data and here and I'll create you jsfiddle with how it will work

**Comment by probil** [comment]
@madsongr https://jsfiddle.net/probil/m6jnpv7g/

**Comment by madsongr** [comment]
Hi @probil. Yes it is an object. I'm already looping using a `v-for` as I mentioned in my question. Here is my code:
```
<div class="row host-row" v-for="user in hosts">
    <div class="col-md-5">
        <div class="messages-profile-infos">
            <div class="messages-profile-infos-img">
                <div class="pics-list-image-container img-fluid" v-bind:style="{'background-image': 'url(https://website.com/backend/users/'+ user.profileIMG + ')' }"></div>
            </div>
            <div class="messages-profile-infos-text">
                <p>{{ user.username }} {{ user.lastname }}</p>
                <p>{{ user.city }} - {{user.state}}</p>
                <p>CPF: {{ 'user.cpf' | VMask('###.###.###-##') }}</p>
                <p>E-mail: {{ user.email }}</p>
                <p>Contato: {{ 'user.cellphone' | VMask('(##) # ####-####') }}</p>
            </div>
        </div>
    </div>
</div>
```

**Comment by probil** [comment]
@madsongr Check the jsfiddle above https://github.com/probil/v-mask/issues/510#issuecomment-764905343

This should work:
```vue
<div class="row host-row" v-for="user in hosts">
    <div class="col-md-5">
        <div class="messages-profile-infos">
            <div class="messages-profile-infos-img">
                <div class="pics-list-image-container img-fluid" v-bind:style="{'background-image': 'url(https://website.com/backend/users/'+ user.profileIMG + ')' }"></div>
            </div>
            <div class="messages-profile-infos-text">
                <p>{{ user.username }} {{ user.lastname }}</p>
                <p>{{ user.city }} - {{user.state}}</p>
                <p>CPF: {{ user.cpf | VMask('###.###.###-##') }}</p>
                <p>E-mail: {{ user.email }}</p>
                <p>Contato: {{ user.cellphone | VMask('(##) # ####-####') }}</p>
            </div>
        </div>
    </div>
</div>

**Comment by madsongr** [comment]
@probil yep I tried that but this is the error that I get:

![image](https://user-images.githubusercontent.com/4735867/105519117-d3603400-5cb7-11eb-9a9c-7358a217993f.png)

I even tried to change vue.min.js to the link you have in docs but I get the same error/result. I think I'm going to handle that with jquery

**Comment by probil** [comment]
@madsongr Got it. As you see in my jsfiddle - it works fine. There might a different problem like `null`, `undefined` or some exotic data types in `cpf` or `cellphone` of your hosts.

**Comment by probil** [comment]
@madsongr Found it. It throws the same error when value is `null`:
https://jsfiddle.net/probil/m6jnpv7g/5/

Need some time to fix it and write a test to prevent it happening in the future. As a temporal solution you can use this trick:
```vue
<p>Contato: {{ (user.cellphone || '') | VMask('(##) # ####-####') }}</p>
```
https://jsfiddle.net/probil/m6jnpv7g/7/

**Comment by probil** [comment]
@madsongr Found it. It throws the same error when value is `null`:
https://jsfiddle.net/probil/m6jnpv7g/5/

Need some time to fix it and write a test to prevent it happening in the future. As a temporal solution you can use this trick:
```vue
<p>Contato: {{ (user.cellphone || '') | VMask('(##) # ####-####') }}</p>
```

**Comment by madsongr** [comment]
@probil Great! It worked very well. Thank you so much for your time.

**Comment by probil** [comment]
@madsongr You are welcome. Thanks for reporting and tracing it with me. Will ping you when the fix is released so you can remove the temporary solution. Have a nice day!

**Comment by madsongr** [comment]
@probil Ok. Have a nice day you too!
