### ISSUE TITLE
Bug with phone mask

### ISSUE THREAD

**Issue by shrpne** [probil/v-mask#53]
For masks like `+1 ### ### ####` it will not allow to write `+1 1`.
So if you will type `111` in this input, value becomes `+1 `, and will not change, until you press something except `1`

Same for `+1(###)-###-####` and `+1##########`
Used v-mask 1.2.0 and vue 2.2.6

Example: https://jsfiddle.net/ym03cq9r/

Despite of this, same mask on demo page works fine, i assume there are used not latest version of v-mask

**Comment by probil** [comment]
Sounds like a bug. I will check

**Comment by probil** [comment]
I think the `format` module should be rewriten in functional way. Because current implementation is buggy. It's not easy to explain / maintain / improve the algorithm

**Comment by probil** [comment]
Fixed in `v2.0.0` and up
