### ISSUE TITLE
index.js missing from /dist on 1.3

### ISSUE THREAD

**Issue by justinweinberg** [probil/v-mask#56]
index.js missing from /dist on 1.3

**Comment by probil** [comment]
It's ok. I can't see where it's used. Currently
```
/dist/index.js -> /dist/v-mask.js 
                     -> /dist/v-mask.min.js
                     -> /dist/v-mask.esm.js
```

**Comment by probil** [comment]
Show me where you get the error and I will help to solve it quickly

**Comment by justinweinberg** [comment]
Hi there.    This line isn't happy that index.js doesnt exist in the npm dist folder:

      import VueMask  from 'v-mask'

**Comment by probil** [comment]
Hmm.. Strange. Works just fine for me in `v-mask--demo`
https://github.com/probil/v-mask--demo/blob/master/src/main.js

**Comment by probil** [comment]
@justinweinberg 
Please, provide more info about your configuration. It maybe some custom config of webpack alias or something similar in browserify

**Comment by justinweinberg** [comment]
Closing it.  it was my configuration.  thanks for your help.

**Comment by probil** [comment]
@justinweinberg I'm glad to hear that everything is good for you.
