### ISSUE TITLE
Mask with pre char.

### ISSUE THREAD

**Issue by gabrielbuzziv** [probil/v-mask#6]
I got a problem with the mask when trying to use something like (##) ####-####
What happens is that when the i type the first char, the mask will ignore cause expect a '(', but the right way is that the mask should skip this.

**Comment by johnsoons** [comment]
I'm also having the same problem.

**Comment by diogopaulino** [comment]
@gabrielbuzziv @johnsoons 

I solved this problem just adding a new verification:

`function format(data, mask) {
  var text = '';
  var c, m, i, x;

  for (i = 0, x = 1; x && i < mask.length; ++i) {
    c = data.charAt(i);
    m = mask.charAt(i);

    switch (m) {
      case '#':
        if (/\d/.test(c)) {
          text += c;
        } else {
          x = 0;
        }
        break;

      case 'A':
        if (/[a-z]/i.test(c)) {
          text += c;
        } else {
          x = 0;
        }
        break;

      case 'N':
        if (/[a-z0-9]/i.test(c)) {
          text += c;
        } else {
          x = 0;
        }
        break;

      case 'X':
        text += c;
        break;

      default:
        text += m;
        if (data.length == 1) {
          text += c;
        }
        break;
    }
  }
  return text;
}`

**Comment by gabrielbuzziv** [comment]
@diogopaulino i overwrite it in the format.js, but don't work :X

**Comment by diogopaulino** [comment]
@gabrielbuzziv 

Are you using Vue 1.x?

You just need to replace the "default" case condition at line:
https://github.com/probil/v-mask/blob/vue-1.x/index.js#L22

`default  : text += m; break;`

to this:

`
default:
 text += m;
 if (data.length == 1) {
  text += c;
 }
break;
`

**Comment by gabrielbuzziv** [comment]
@diogopaulino did it, but not working, i will create my own directive for mask, no problem, thanks :D
