### ISSUE TITLE
'Event is not a constructor' error everytime I type in v-mask

### ISSUE THREAD

**Issue by msmadeira** [probil/v-mask#63]
On every place I use v-mask, every change that i have on the text throws an 'Event is not a constructor' error.

It works normally and the way expected, but keeps throwing this error. Anyone knows what could be?

**Comment by probil** [comment]
Hi, @msmadeira . Thanks for your issue.
Could you please, give me more information about environment you are using `v-mask`? At least:
1) `v-mask` version
2) Browser and version
3) Operation System

**Comment by probil** [comment]
Closed due to inactivity
