### ISSUE TITLE
BUG: ? Optional (next character) - does not work

### ISSUE THREAD

**Issue by hagcin** [probil/v-mask#65]
When using the the optional '?' character, a question mark shows up in the output.

**USE CASE:**
'##/##/##?##'  
To allow for: 05/05/95 and 05/05/1995

**Input:** 
05/05/1995

**Expected Result:**
05/05/1995

**Actual Result:**
05/05/19?95

**Comment by birdy247** [comment]
I am trying to get something similar for a currency.

'#?#?#.##'

except the ? does not allow 5.20 or 15.20 only 152.0  Is this possible?

**Comment by NaldoColella** [comment]
Here happens same thing, using '(##) ########?#' when typing the last char it adds for a moment the '?' in the input. Strange... 
BUT the value is okay, doesnt 'bug' the final result

**Comment by probil** [comment]
@NaldoColella I'm currently working on better tests for the codebase. It should help to fix such cases

**Comment by clemsontiger** [comment]
I'm having same problem as birdy247, v-mask="'#?#.##'" isn't allowing for 4.99 and 49.99 but instead gives 49.9 when 4.99 is the value.

**Comment by probil** [comment]
Fixed in `v2.0.0` and up
