### ISSUE TITLE
A way to test lowered/uppered case ?

### ISSUE THREAD

**Issue by kl3sk** [probil/v-mask#67]
ex: ``###-###-###?AA``

match:
 `123-123-132AA`
and
 `123-123-123aa`

But: `###-###-###aa`

match:
 `123-123-123aa` only

**Comment by probil** [comment]
@kl3sk Thanks for your issue. Actually, yes, `v-mask` doesn't include different placeholders for uppercased and lowercased characters. Marked as `feature request`

**Comment by probil** [comment]
We need some kind of technique to separate string chars from mask chars in the mask 🤔

**Comment by probil** [comment]
Directly related to
https://github.com/probil/v-mask/issues/128

**Comment by Pmurs** [comment]
It would feel intuitive to have mask characters be escapable via a "\" much like a regular string. To match the literal "AA", you'd type "\A\A".

**Comment by probil** [comment]
@Pmurs 🤔 valid point

**Comment by probil** [comment]
Feature is part of #128 now. Please continue discussion there
