### ISSUE TITLE
Add support of custom elements

### ISSUE THREAD

**Issue by probil** [probil/v-mask#79]
For example Element UI and other input wrappers:
```html
<el-input v-mask="...." />
```

**Comment by dzarezenko** [comment]
Hi. Looks like it still doesn't work with Element UI.

**Comment by pixiefrog** [comment]
Here's a working example if it helps:
https://codesandbox.io/s/mo4r3857vj

**Comment by dzarezenko** [comment]
> Here's a working example if it helps:
> https://codesandbox.io/s/mo4r3857vj

Thanks! But looks like you have used completely other package.

**Comment by pixiefrog** [comment]
Oh boy, how did i miss that. Sorry.

**Comment by probil** [comment]
😄  Thanks @dzarezenko
