### ISSUE TITLE
not working properly on Vue 2.0

### ISSUE THREAD

**Issue by paulvl** [probil/v-mask#8]
Hello,

I used version 0.1.0 with no problems, but now I'm writing an application with vue 2.0,
and v-mask version 1.0.1 doesn't work properly, for example for '###':

I type 'a':
Input : display a

then I type anything:
Input: remove a, and display nothing

then I type 1:
Input: displays 1, and after that everything is good as always.

In other words, the first character is not being recognized by the directive, and in some way is overwritten by the second one.

Hope you can fix this.

**Comment by flip-santos** [comment]
Hey @paulvl, I had a similar issue here that result in this solution: https://github.com/probil/v-mask/pull/9 . Can you confirm if this resolve your issue?

Thanks!

**Comment by paulvl** [comment]
@flip-santos according to @probil 's fix it should work, I cant test it now but I'll as soon as possible =)

**Comment by probil** [comment]
Merged. Try to pull `v1.0.2` from the `npm`. Demo also updated.
